services:
  claudepod:
    build:
      context: .
      network: host
    image: oh-my-claudepod:0.4.0.dev5
    container_name: claudepod
    stdin_open: true
    tty: true
    working_dir: /workspace
    volumes:
      - ${PROJECT_DIR:-.}:/workspace
    network_mode: host
    restart: "no"
