#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

omd_source_config_header="# Generated by oh-my-devpod. Managed native source configuration."

omd_source_config_path_is_safe() {
  local path="$1" trusted_root="$2" current parent
  [[ "${path}" == /* && "${trusted_root}" == /* ]] || return 1
  [[ "${path}" == "${trusted_root}"/* ]] || return 1
  [[ ! -L "${path}" ]] || return 1
  current="$(dirname "${path}")"
  while [[ "${current}" != "${trusted_root}" ]]; do
    [[ ! -L "${current}" ]] || return 1
    parent="$(dirname "${current}")"
    [[ "${parent}" != "${current}" ]] || return 1
    current="${parent}"
  done
}

omd_source_config_atomic_write() {
  local destination="$1" trusted_root="$2" directory temporary
  omd_source_config_path_is_safe "${destination}" "${trusted_root}" || {
    omd_module_info error "refusing unsafe source configuration path: ${destination}"
    return 1
  }
  directory="$(dirname "${destination}")"
  mkdir -p "${directory}" || return 1
  temporary="$(mktemp "${directory}/.$(basename "${destination}").tmp.XXXXXX")" ||
    return 1
  if ! cat > "${temporary}"; then
    rm -f "${temporary}"
    return 1
  fi
  if ! mv -f "${temporary}" "${destination}"; then
    rm -f "${temporary}"
    return 1
  fi
}

omd_source_config_formula_prefix() {
  local component="$1" formula="$2" prefix
  prefix="$(omd_module_formula_marker_prefix "${component}" "${formula}")" || return 1
  omd_module_brew_formula_installed_at "${prefix}" "${formula}" || return 1
  printf '%s\n' "${prefix}"
}

omd_source_config_formula_managed() {
  omd_source_config_formula_prefix "$1" "$2" >/dev/null
}

omd_source_config_linuxbrew_prefix() {
  local prefix kind brew
  omd_module_is_managed linuxbrew || return 1
  prefix="$(omd_module_marker_value linuxbrew artifact || true)"
  kind="$(omd_module_marker_value linuxbrew kind || true)"
  [[ "${kind}" == "directory" && -n "${prefix}" && ! -L "${prefix}" && -x "${prefix}/bin/brew" ]] ||
    return 1
  prefix="$(cd "${prefix}" 2>/dev/null && pwd -P)" || return 1
  if omd_shared_linuxbrew_managed; then
    brew="$(omd_shared_linuxbrew_gateway)"
  else
    brew="${prefix}/bin/brew"
  fi
  omd_module_brew_cmd_matches_prefix "${brew}" "${prefix}" || return 1
  printf '%s\n' "${prefix}"
}

omd_source_config_uv_path() {
  printf '%s/uv/uv.toml\n' "${XDG_CONFIG_HOME:-${HOME}/.config}"
}

omd_source_config_config_home() {
  printf '%s\n' "${XDG_CONFIG_HOME:-${HOME}/.config}"
}

omd_source_config_pip_path() {
  printf '%s/pip/pip.conf\n' "${XDG_CONFIG_HOME:-${HOME}/.config}"
}

omd_source_config_mamba_path() {
  printf '%s/.mambarc\n' "${HOME}"
}

omd_source_config_expected() {
  local kind="$1"
  case "${kind}" in
    brew)
      cat <<EOF
${omd_source_config_header}
HOMEBREW_BREW_GIT_REMOTE=https://mirrors.ustc.edu.cn/brew.git
HOMEBREW_CORE_GIT_REMOTE=https://mirrors.ustc.edu.cn/homebrew-core.git
HOMEBREW_API_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles/api
HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles
EOF
      ;;
    uv)
      cat <<EOF
${omd_source_config_header}
[[index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
EOF
      ;;
    pip)
      cat <<EOF
${omd_source_config_header}
[global]
index-url = https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
EOF
      ;;
    mamba)
      cat <<EOF
${omd_source_config_header}
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
channels:
  - conda-forge
EOF
      ;;
    *)
      return 2
      ;;
  esac
}

omd_source_config_file_is_managed() {
  local kind="$1" path="$2" actual expected
  [[ -f "${path}" && ! -L "${path}" ]] || return 1
  actual="$(cat "${path}")" || return 1
  expected="$(omd_source_config_expected "${kind}")" || return 1
  [[ "${actual}" == "${expected}" ]]
}

omd_source_config_active_paths() {
  local prefix need_pip=0
  if ! omd_shared_linuxbrew_managed && prefix="$(omd_source_config_linuxbrew_prefix)"; then
    printf 'brew\t%s/etc/homebrew/brew.env\t%s\n' "${prefix}" "${prefix}"
  fi
  if omd_source_config_formula_managed uv uv; then
    printf 'uv\t%s\t%s\n' \
      "$(omd_source_config_uv_path)" \
      "$(omd_source_config_config_home)"
    need_pip=1
  fi
  if omd_source_config_formula_managed micromamba micromamba; then
    printf 'mamba\t%s\t%s\n' "$(omd_source_config_mamba_path)" "${HOME}"
    need_pip=1
  fi
  if [[ "${need_pip}" == "1" ]]; then
    printf 'pip\t%s\t%s\n' \
      "$(omd_source_config_pip_path)" \
      "$(omd_source_config_config_home)"
  fi
}

omd_source_config_validate() {
  local source="$1" kind path trusted_root
  case "${source}" in
    github|gitee) ;;
    *) return 2 ;;
  esac

  while IFS=$'\t' read -r kind path trusted_root; do
    [[ -n "${kind}" && -n "${path}" && -n "${trusted_root}" ]] || continue
    if ! omd_source_config_path_is_safe "${path}" "${trusted_root}"; then
      omd_module_info error "refusing unsafe source configuration path: ${path}"
      return 1
    fi
    if [[ -e "${path}" || -L "${path}" ]] &&
      ! omd_source_config_file_is_managed "${kind}" "${path}"; then
      omd_module_info error "refusing to overwrite user-modified source configuration: ${path}"
      return 1
    fi
  done < <(omd_source_config_active_paths)
}

omd_source_config_apply() {
  local source="$1" kind path trusted_root
  omd_source_config_validate "${source}" || return

  while IFS=$'\t' read -r kind path trusted_root; do
    [[ -n "${kind}" && -n "${path}" && -n "${trusted_root}" ]] || continue
    if [[ "${source}" == "gitee" ]]; then
      omd_source_config_expected "${kind}" |
        omd_source_config_atomic_write "${path}" "${trusted_root}" ||
        return 1
    else
      if [[ -e "${path}" || -L "${path}" ]]; then
        rm -f "${path}" || return 1
      fi
    fi
  done < <(omd_source_config_active_paths)
}

omd_source_config_apply_transactional() {
  local source="$1" transaction_root transaction_dir rollback_failed=0
  transaction_root="${OHMYDEVPOD_SOURCE_CONFIG_TRANSACTION_ROOT:-$(omd_module_state_dir)}"
  mkdir -p "${transaction_root}" || return 1
  transaction_dir="$(mktemp -d "${transaction_root}/.source-config.XXXXXXXX")" ||
    return 1
  if ! omd_source_config_validate "${source}" ||
    ! omd_source_config_snapshot "${transaction_dir}"; then
    rm -rf "${transaction_dir}"
    return 1
  fi
  if omd_source_config_apply "${source}"; then
    rm -rf "${transaction_dir}"
    return 0
  fi
  omd_source_config_restore "${transaction_dir}" || rollback_failed=1
  if [[ "${rollback_failed}" == "0" ]]; then
    rm -rf "${transaction_dir}"
  else
    omd_module_info error "native source rollback was incomplete: ${transaction_dir}"
  fi
  return 1
}

omd_source_config_snapshot() {
  local snapshot_dir="$1" kind path trusted_root
  mkdir -p "${snapshot_dir}" || return 1
  : > "${snapshot_dir}/native-paths"
  while IFS=$'\t' read -r kind path trusted_root; do
    [[ -n "${kind}" && -n "${path}" && -n "${trusted_root}" ]] || continue
    printf '%s\t%s\t%s\n' "${kind}" "${path}" "${trusted_root}" \
      >> "${snapshot_dir}/native-paths"
    if [[ -f "${path}" ]]; then
      cp -p "${path}" "${snapshot_dir}/native-${kind}" || return 1
    else
      : > "${snapshot_dir}/.missing-native-${kind}" || return 1
    fi
  done < <(omd_source_config_active_paths)
}

omd_source_config_restore() {
  local snapshot_dir="$1" kind path trusted_root
  [[ -f "${snapshot_dir}/native-paths" ]] || return 0
  while IFS=$'\t' read -r kind path trusted_root; do
    [[ -n "${kind}" && -n "${path}" && -n "${trusted_root}" ]] || continue
    if ! omd_source_config_path_is_safe "${path}" "${trusted_root}"; then
      omd_module_info error "refusing unsafe source configuration rollback path: ${path}"
      return 1
    fi
    if [[ -f "${snapshot_dir}/.missing-native-${kind}" ]]; then
      if [[ -e "${path}" || -L "${path}" ]] &&
        ! omd_source_config_file_is_managed "${kind}" "${path}"; then
        omd_module_info error "refusing to remove changed source configuration during rollback: ${path}"
        return 1
      fi
      if [[ -e "${path}" || -L "${path}" ]]; then
        rm -f "${path}" || return 1
      fi
    else
      cat "${snapshot_dir}/native-${kind}" |
        omd_source_config_atomic_write "${path}" "${trusted_root}" ||
        return 1
    fi
  done < "${snapshot_dir}/native-paths"
}

omd_source_config_remove_managed_file() {
  local kind="$1" path="$2" trusted_root="$3"
  [[ -e "${path}" || -L "${path}" ]] || return 0
  if ! omd_source_config_path_is_safe "${path}" "${trusted_root}"; then
    omd_module_info notice "preserving unsafe source configuration path: ${path}"
    return 0
  fi
  if omd_source_config_file_is_managed "${kind}" "${path}"; then
    rm -f "${path}"
  else
    omd_module_info notice "preserving modified source configuration: ${path}"
  fi
}

omd_source_config_remove_component() {
  local component="$1"
  case "${component}" in
    uv)
      omd_source_config_remove_managed_file \
        uv \
        "$(omd_source_config_uv_path)" \
        "$(omd_source_config_config_home)" ||
        return 1
      if ! omd_source_config_formula_managed micromamba micromamba; then
        omd_source_config_remove_managed_file \
          pip \
          "$(omd_source_config_pip_path)" \
          "$(omd_source_config_config_home)"
      fi
      ;;
    micromamba)
      omd_source_config_remove_managed_file \
        mamba \
        "$(omd_source_config_mamba_path)" \
        "${HOME}" ||
        return 1
      if ! omd_source_config_formula_managed uv uv; then
        omd_source_config_remove_managed_file \
          pip \
          "$(omd_source_config_pip_path)" \
          "$(omd_source_config_config_home)"
      fi
      ;;
    *)
      return 2
      ;;
  esac
}
